version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the image and push it
          command: project/.circleci/circle-deploy-image.sh
#      - checkout
#      - run: go get -u github.com/golang/dep/cmd/dep
#      - run: go get -u github.com/tcnksm/ghr
#      - run: go get -u github.com/stevenmatthewt/semantics
#      - run:
#          name: run build
#          command: |
#            dep ensure
#            CGO_ENABLED=0 GOOS=linux go install -a github.com/favish/dynamic-vmap
#      - add_ssh_keys:
#          fingerprints:
#            - "3f:26:f2:4d:90:4c:ba:8c:9e:f7:d1:c7:29:56:89:d9"
#      - run:
#          name: create release
#          command: |
#            tag=$(semantics --output-tag)
#            if [ "$tag" ]; then
#              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag /go/bin/dynamic-vmap
#            else
#              echo "The commit message(s) did not indicate a major/minor/patch version."
#            fi