version: 2
workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: add git
          command: apk add git
      - run:
          name: helm-github-pages
          command: cat .circleci/publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: favish/dynamic-vmap