version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name: helm-github-pages
          command: cat .circleci/publish.sh | sh
          environment:
            - GITHUB_PAGES_REPO: favish/dynamic-vmap