version: 2
jobs:
  build:
    - steps:
      - checkout
      - run:
        name: helm-github-pages
        environment:
          - GITHUB_PAGES_REPO: favish/dynamic-vmap
        command: .circleci/publish.sh | sh